### ISSUE TITLE
사이트랑 깃허브 프로필 연동 

### ISSUE THREAD

**Issue by git-good-w** [git-goods/git-animal-client#105]
안되나요 ?? 토끼뽑아서 추가했는데 깃헙 프로필에는 적용안되는거같아서요 .. 사용법이 따로있는가하구요

**Comment by devxb** [comment]
@sumi-0011 @hyesungoh 

여기도 Assignees가 안걸려있네요 🤔 

이런 류의 요청이 아닌 대답을 듣고싶어하는 경우는 어떻게 처리할지 고민해봐야 할듯 합니다.
채널톡은 대화형으로 응대가 가능한데, 저희는 그런 구조는 아닌거 같아서요. 
- Assignees가 있으면, 이슈에 응답할때, 해당 유저를 @ 해서 태그한다던가..?
- 이슈에 댓글달면 메일로 답을 준다던가..?

근데 요거 옮겨주시면 감사하겠습니당 🙏
