### ISSUE TITLE
배럴 파일에서는 default export가 아닌 named export

### ISSUE THREAD

**Issue by sumi-0011** [git-goods/git-animal-client#116]
관련 이슈 -> https://github.com/git-goods/git-animal-client/pull/111#discussion_r1667609156

-->  lint rule을 찾거나 만들어서 적용해보기

**Comment by hyesungoh** [comment]
아아 제가 드리고 싶었던 말씀은

'린트로 잡히지 않는 것들을 컨벤션으로 정할 필요가 있을까?' 입니당 🤔 🤔 🤔 🤔

**Comment by sumi-0011** [comment]
전에 잠시 확인해보았는데, 린트로 이를 잡을 수 있더라구요!
그런데 전체 파일이 아닌 특정 파일에서만 잡는 방법을 아직 찾지 못했습니다 🤔
