### ISSUE TITLE
Refactor: React Query Key 관리 방식 변경하기

### ISSUE THREAD

**Issue by sumi-0011** [git-goods/git-animal-client#20]
참고 : https://www.zigae.com/react-query-key/

**Comment by hyesungoh** [comment]
https://github.com/lukemorales/query-key-factory

공식 문서에서도 소개되고, 우아콘에서도 나왔던 라이브러린데 공유드려용

**Comment by sumi-0011** [comment]
> https://github.com/lukemorales/query-key-factory
> 
> 공식 문서에서도 소개되고, 우아콘에서도 나왔던 라이브러린데 공유드려용

공유 감사합니다!
개인적으로 외부 라이브러리를 사용하는 지양하는 편인데,, 혜성님도 비슷하다고 알고있어요
이 라이브러리를 공유해주신것은 이 라이브러리의 방식을 공유해주고 싶은걸까요 아니면 라이브러리 사용을 추천해주신걸까요?

**Comment by hyesungoh** [comment]
@sumi-0011 
사용하자는 의도 보다는 `이런 것도 있다더라~` 였습니다 ~

저는 개인적으로 서비스 규모가 크진 않다보니, 상수로만 관리해도 충분할 것 같아요 🤔
