### ISSUE TITLE
farm Type에서는 캐릭터가 많은데 적용이 느린가요??

### ISSUE THREAD

**Issue by git-good-w** [git-goods/git-animal-client#90]
github 홈페이지에서는 캐릭터 일부가 없는데 이게 반영이좀 느린걸까요??

**Comment by sumi-0011** [comment]
@hyesungoh 혹시 해당 이슈 처음부터 assinged에 아무도 없었나요?

**Comment by hyesungoh** [comment]
> @hyesungoh 혹시 해당 이슈 처음부터 assinged에 아무도 없었나요?

넹
